#!/bin/bash

while true
do
    echo "-------------------------"
    echo "      MAIN MENU"
    echo "-------------------------"
    echo "1. Show Date and Time"
    echo "2. List Files"
    echo "3. Current Directory"
    echo "4. Who is logged in"
    echo "5. Exit"
    echo "-------------------------"
    read -p "Enter your choice [1-5]: " choice

    case $choice in
        1)
            echo "Date and Time: $(date)"
            ;;
        2)
            echo "Files in current directory:"
            ls
            ;;
        3)
            echo "Current directory: $(pwd)"
            ;;
        4)
            who
            ;;
        5)
            echo "Exiting program. Bye!"
            break
            ;;
        *)
            echo "Invalid choice. Please enter a number between 1 and 5."
            ;;
    esac
    echo "" # Print a newline for better readability
done
